name: ci

on:
  push:
    branches: [main]

jobs:
  docker-image:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run prisma:generate
      - run: docker compose up -d
      - run: npm run prisma:db:push && npm run test && npm run prisma:reset
      - run: docker compose down
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{github.repository}}:${{github.ref_name}}
